version: '3'
services:
 
 docker:
  image: docker:dind
  restart: always
  privileged: true
 
 desktop:
  build:
   context: desktop/
  # image: marcelmaatkamp/alpine-xfce4-xrdp
  restart: always
  ports:
   - "3389:3389"
   - "4848:22"
  environment: 
   - DOCKER_HOST=tcp://docker:2375
   - BOE=BLA
 
